import Navbar2 from "./components/Navbar2";
import { Providers } from "@/app/Redux/provider";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "ECommerce",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html  lang="en" data-theme="luxury">

      <body className={inter.className}>
      <Providers>
          <Navbar2/>
          {children}
          </Providers>
        <script
          src="https://kit.fontawesome.com/64f1d7bfe6.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
